---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nindevdo
  region: us-west-2

nodeGroups:
  - name: nindevdo-node-group-1
    instanceType: t2.small
    desiredCapacity: 1

cloudWatch:
    clusterLogging:
        enableTypes: ["audit", "authenticator", "controllerManager"]